# CONSTRUCCION EN BUILD
FROM php:8.3-fpm-alpine
WORKDIR /var/www
RUN apk add --no-cache bash curl libpng-dev oniguruma-dev libxml2-dev zip unzip
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Copiamos composer.json de aqui
COPY composer.json ./
RUN composer install --no-scripts --no-autoloader --prefer-dist
COPY . .
RUN composer dump-autoload --optimize
EXPOSE 9000
CMD ["php-fpm"]
